name: DOTIE
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - appdirs=1.4.4
  - arrow=1.2.2
  - astroid=2.6.6
  - atomicwrites=1.4.0
  - attrs=21.4.0
  - autopep8=1.6.0
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.10.0
  - binaryornot=0.4.4
  - black=19.10b0
  - blas=1.0
  - bleach=4.1.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - cookiecutter=1.7.3
  - cpuonly=2.0
  - cryptography=36.0.0
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2021.11.2
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - docutils=0.17.1
  - entrypoints=0.4
  - expat=2.4.4
  - ffmpeg=4.3.2
  - flake8=3.9.2
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - fsspec=2022.11.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.66.3
  - gmp=6.2.1
  - gnutls=3.6.15
  - graphite2=1.3.13
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - h5py=2.10.0
  - harfbuzz=2.4.0
  - hdf5=1.10.6
  - icu=64.2
  - idna=3.3
  - imageio=2.19.3
  - imagesize=1.3.0
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - inflection=0.5.1
  - intel-openmp=2022.0.1
  - intervaltree=3.1.0
  - ipykernel=6.9.1
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - isort=5.9.3
  - jasper=1.900.1
  - jbig=2.1
  - jedi=0.18.1
  - jeepney=0.7.1
  - jinja2=3.0.3
  - jinja2-time=0.2.0
  - joblib=1.1.0
  - jpeg=9d
  - jsonschema=4.4.0
  - jupyter_client=6.1.12
  - jupyter_core=4.9.2
  - jupyterlab_pygments=0.1.2
  - keyring=23.4.0
  - kiwisolver=1.3.2
  - lame=3.100
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - lerc=2.2.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libdeflate=1.7
  - libedit=3.1.20210910
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.66.3
  - libgomp=9.3.0
  - libiconv=1.16
  - libidn2=2.3.2
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libllvm9=9.0.1
  - libopencv=4.5.2
  - libpng=1.6.37
  - libprotobuf=3.16.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.3.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - locket=1.0.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - nbclient=0.5.11
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - networkx=2.2
  - ninja=1.10.2
  - nspr=4.30
  - nss=3.59
  - numpy=1.20.3
  - numpy-base=1.17.4
  - numpydoc=1.2
  - opencv=4.5.2
  - openh264=2.1.1
  - openssl=1.0.2u
  - packaging=21.3
  - pandas=1.2.4
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pathspec=0.7.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.2
  - pixman=0.38.0
  - pluggy=1.0.0
  - poyo=0.5.0
  - prompt-toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py-opencv=4.5.2
  - pycodestyle=2.7.0
  - pycparser=2.21
  - pydocstyle=6.1.1
  - pyflakes=2.3.1
  - pygments=2.11.2
  - pylint=2.9.6
  - pyls-spyder=0.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.12.3
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.7.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python-lsp-black=1.0.0
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.2.4
  - python-slugify=5.0.2
  - python_abi=3.7
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - pytz=2021.3
  - pywavelets=1.3.0
  - pyxdg=0.27
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qdarkstyle=3.0.2
  - qstylizer=0.1.10
  - qt=5.12.5
  - qtawesome=1.0.3
  - qtconsole=5.3.0
  - qtpy=2.0.1
  - readline=7.0
  - regex=2022.3.15
  - requests=2.27.1
  - rope=0.22.0
  - rtree=0.9.7
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - scipy=1.6.2
  - secretstorage=3.3.1
  - setuptools=59.8.0
  - sip=4.19.8
  - six=1.16.0
  - snntorch=0.5.1
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sphinx=4.4.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.1.5
  - spyder-kernels=2.1.3
  - sqlite=3.33.0
  - testpath=0.5.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=2.2.0
  - three-merge=0.1.1
  - tifffile=2020.10.1
  - tinycss=0.4
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.12.0
  - torchvision=0.11.0
  - tornado=6.1
  - traitlets=5.1.1
  - typed-ast=1.4.3
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - ujson=5.1.0
  - unidecode=1.2.0
  - urllib3=1.26.8
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - wrapt=1.12.1
  - wurlitzer=3.0.2
  - x264=1!161.3030
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.2
  - xorg-libx11=1.7.2
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.12
  - zstd=1.5.0
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1

